version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    volumes:
      - ./dockermysql:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=mticket
      - MYSQL_ROOT_PASSWORD=1