# Generated by Django 2.0.3 on 2018-04-12 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180411_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.IntegerField(default=0)),
                ('leader', models.IntegerField(default=0)),
            ],
            options={
                'managed': True,
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='TicketAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Agents')),
            ],
            options={
                'managed': True,
                'db_table': 'ticket_agent',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('datestart', models.DateTimeField()),
                ('dateend', models.DateTimeField()),
            ],
            options={
                'managed': True,
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'managed': True,
                'db_table': 'topics',
            },
        ),
        migrations.RenameModel(
            old_name='UserUsers',
            new_name='Users',
        ),
        migrations.AddField(
            model_name='tickets',
            name='sender',
            field=models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Users'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Topics'),
        ),
        migrations.AddField(
            model_name='ticketagent',
            name='ticketid',
            field=models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Tickets'),
        ),
    ]
