# Generated by Django 2.0.4 on 2018-04-13 02:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180412_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='attach',
            field=models.ImageField(default=None, storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
            preserve_default=False,
        ),
    ]
