# Generated by Django 2.0.5 on 2018-06-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_ticketlog_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='noti_chat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agents',
            name='noti_noti',
            field=models.IntegerField(default=0),
        ),
    ]
