# Generated by Django 2.0.5 on 2018-06-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20180607_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='noti_chat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='noti_noti',
            field=models.IntegerField(default=0),
        ),
    ]
