# Generated by Django 2.0.5 on 2018-07-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='type_send',
        ),
    ]
