# Generated by Django 2.0.5 on 2018-07-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_topics_type_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='departmentid',
            field=models.ForeignKey(db_column='departmentid', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Departments'),
        ),
    ]
