# Generated by Django 2.0.5 on 2018-07-04 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180704_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='departmentid',
            field=models.ForeignKey(db_column='departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Departments'),
        ),
    ]
