# Generated by Django 2.0.5 on 2018-07-04 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180704_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='agentid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='ticketid',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userid',
        ),
        migrations.AlterField(
            model_name='topics',
            name='departmentid',
            field=models.ForeignKey(db_column='departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Departments'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
