# Generated by Django 2.0.5 on 2018-05-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tickets_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('date', models.DateField()),
                ('weekday', models.TextField()),
                ('time', models.TimeField()),
                ('agentid', models.ForeignKey(db_column='agentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenttl', to='user.Agents')),
                ('ticketid', models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, related_name='tickettl', to='user.Tickets')),
                ('userid', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertl', to='user.Users')),
            ],
            options={
                'db_table': 'ticket_log',
                'managed': True,
            },
        ),
    ]
