# Generated by Django 2.0.5 on 2018-05-17 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_ticketlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='weekday',
        ),
    ]
