# Generated by Django 2.0.5 on 2018-07-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180613_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.CASCADE, to='user.Agents')),
                ('topicid', models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.DO_NOTHING, to='user.Topics')),
            ],
            options={
                'db_table': 'topic_agent',
                'managed': True,
            },
        ),
    ]
