# Generated by Django 2.0.5 on 2018-07-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_topicagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicagent',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.CASCADE, to='user.Topics'),
        ),
    ]
