# Generated by Django 2.0.3 on 2018-04-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addagents',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forwardtickets',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
