# Generated by Django 2.0.3 on 2018-04-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userusers',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
