# Generated by Django 2.0.3 on 2018-04-20 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180420_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addagents',
            name='receiverid',
            field=models.ForeignKey(db_column='receiverid', on_delete=django.db.models.deletion.CASCADE, related_name='receiveradd', to='user.Agents'),
        ),
        migrations.AlterField(
            model_name='addagents',
            name='senderid',
            field=models.ForeignKey(db_column='senderid', on_delete=django.db.models.deletion.CASCADE, related_name='senderadd', to='user.Agents'),
        ),
        migrations.AlterField(
            model_name='addagents',
            name='ticketid',
            field=models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, to='user.Tickets'),
        ),
    ]
