# Generated by Django 2.0.4 on 2018-04-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180423_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('agentid', models.ForeignKey(db_column='agentid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcm', to='user.Agents')),
                ('ticketid', models.ForeignKey(db_column='ticketid', on_delete=django.db.models.deletion.CASCADE, related_name='ticketcm', to='user.Tickets')),
                ('userid', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercm', to='user.Users')),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
    ]
