# Generated by Django 2.0.4 on 2018-04-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tickets_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='attach',
            field=models.FileField(upload_to='photos'),
        ),
    ]
