# Generated by Django 2.0.5 on 2018-05-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='chat',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
