# Generated by Django 2.0.4 on 2018-04-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180413_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='photos'),
        ),
    ]
